### ISSUE TITLE
Hello, may I ask why Scoliovis.app cannot be used

### ISSUE THREAD

**Issue by dujiabao123** [Blankeos/scoliovis#1]
![1719920193979](https://github.com/Blankeos/scoliovis/assets/129504455/41a31f1b-d588-4674-8b12-5d1d1cf5dfc5)

**Comment by Blankeos** [comment]
Hi @1coke2, I halted the python server that's running the model. It's pretty expensive to run: About $20/month on Railway. This project doesn't make money so I don't wanna bleed out running a personal project. Hope you understand.
